name: The Hello World Demo
on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
        - name: Pull My Code
          uses: actions/checkout@v2  # A script which pull the repo that triggers this action
        - name: Setup Environment
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            tools: composer:v2
        - name: Say Hello!
          run: echo "Hello Thomas"
        - name: Show PHP Version
          run: php -v
        - name: Show Composer Version
          run: composer -v
        - name: Install laravel
          run: composer install
        - name: test app
          run: php artisan test
  deploy-app:
    needs:
      - test-app
    runs-on: ubuntu-latest
    steps:
      - name: deploying code
        run: echo "app getting deployed"

